# Generated by Django 5.1.4 on 2026-05-04 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('team.invitation_sent', 'You were invited to a team'), ('team.invitation_accepted', 'Your invitation was accepted'), ('team.invitation_rejected', 'Your invitation was rejected'), ('team.member_joined', 'Someone joined the team'), ('team.member_left', 'Someone left the team'), ('team.member_removed', 'You were removed from a team'), ('team.role_promoted', 'You were promoted to admin'), ('team.role_demoted', 'You were demoted from admin'), ('team.deleted', 'A team you belong to was deleted'), ('calendar.sync_failed', 'A calendar failed to sync')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
            },
        ),
    ]
