# Generated by Django 5.1.4 on 2026-05-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('team.invitation_sent', 'You were invited to a team'), ('team.invitation_accepted', 'Your invitation was accepted'), ('team.invitation_rejected', 'Your invitation was rejected'), ('team.member_added', 'You were added to a group'), ('team.member_joined', 'Someone joined the team'), ('team.member_left', 'Someone left the team'), ('team.member_removed', 'You were removed from a team'), ('team.role_promoted', 'You were promoted to admin'), ('team.role_demoted', 'You were demoted from admin'), ('team.deleted', 'A team you belong to was deleted'), ('calendar.sync_failed', 'A calendar failed to sync'), ('connection.requested', 'Someone wants to connect with you'), ('connection.accepted', 'Your connection request was accepted')], max_length=64),
        ),
    ]
