# Generated by Django 5.1.4 on 2026-05-04 15:56

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_hours',
            field=models.JSONField(default=apps.accounts.models.default_working_hours),
        ),
    ]
