# Generated by Django 5.1.4 on 2026-05-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_notification_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='CZ', max_length=2),
        ),
    ]
