# Generated by Django 5.1.4 on 2026-05-04 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('apple', 'Apple iCloud'), ('outlook', 'Microsoft 365 / Outlook'), ('other', 'Other ICS URL')], default='other', max_length=20)),
                ('url_encrypted', models.TextField()),
                ('include_in_busy', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('syncing', 'Syncing'), ('sync_failing', 'Sync failing'), ('unreachable', 'Unreachable')], default='ok', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_etag', models.CharField(blank=True, max_length=400)),
                ('last_modified', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=512)),
                ('recurrence_id', models.CharField(blank=True, default='', max_length=200)),
                ('dtstart', models.DateTimeField()),
                ('dtend', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('transp', models.CharField(choices=[('opaque', 'Busy'), ('transparent', 'Free')], default='opaque', max_length=20)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.calendar')),
            ],
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['owner', 'include_in_busy'], name='calendars_c_owner_i_fb1e44_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['calendar', 'dtstart'], name='calendars_c_calenda_95c0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['calendar', 'dtend'], name='calendars_c_calenda_e59836_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(fields=('calendar', 'uid', 'recurrence_id'), name='calendarevent_uid_unique_per_calendar'),
        ),
    ]
