# Generated by Django 5.1.4 on 2026-05-05 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_ids', models.JSONField(default=list)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('buffer_min', models.PositiveSmallIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.team')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', '-created_at'], name='search_rece_owner_i_f11b0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('member_ids', models.JSONField(default=list)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('buffer_min', models.PositiveSmallIntegerField(default=0)),
                ('window_days', models.PositiveSmallIntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.team')),
            ],
            options={
                'ordering': ('-last_used_at',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_saved_search_name_per_user')],
            },
        ),
    ]
